name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python for Ansible lint
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install Ansible and ansible-lint
      run: |
        pip install ansible ansible-lint

    - name: Run ansible-playbook
      run: |
        ansible-playbook -i inventory.yml playbook.yml
      working-directory: opdracht2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform init
      run: terraform init
      working-directory: opdracht2

    - name: Terraform apply --auto-approve
      run: terraform apply --auto-approve
      working-directory: opdracht2
