name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint Ansible code
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python for Ansible
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Ansible and ansible-lint
        run: |
          pip install ansible ansible-lint

      - name: Run ansible-lint
        run: |
          ansible-lint playbook.yml
        working-directory: ./opdracht2
        continue-on-error: true 

  terraform:
    name: Terraform provision
    runs-on: self-hosted
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: |
          terraform init
        working-directory: ./opdracht2

      - name: Terraform apply 
        run: |
          terraform apply --auto-approve
        working-directory: ./opdracht2

      - name: cat inventory.ini ter controle
        run: |
          cat inventory.ini && echo "$PWD"
        working-directory: ./opdracht2

      - name: echo pwd ter controle
        run: |
          echo "$PWD"

  deploy:
    name: Run Ansible playbook
    runs-on: self-hosted
    needs: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: echo pwd ter controle
        run: |
          echo "$PWD"

      - name: Run ansible-playbook
        run: |
          ansible-playbook -i inventory.ini playbook.yml
        working-directory: ./opdracht2